//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiceMill5911.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingForm: Myclass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingForm()
        {
            this.BookingDescription = new HashSet<BookingDescription>();
        }
    
        public int BookingID { get; set; }
        public string BookingDate { get; set; }
        public string BookingWant { get; set; }
        public string BookingSubmit { get; set; }
        public Nullable<double> BookingDeliveryFee { get; set; }
        public string EmployeeID { get; set; }
        public string CustomerUsre { get; set; }
        public Nullable<int> StatusBookingID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDescription> BookingDescription { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual StatusBooking StatusBooking { get; set; }
    }
}
