//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiceMill5911.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rice: Myclass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rice()
        {
            this.BookingDescription = new HashSet<BookingDescription>();
            this.BuyDescription = new HashSet<BuyDescription>();
        }
    
        public int RiceID { get; set; }
        public string RiceName { get; set; }
        public Nullable<int> TypeRiceID { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public Nullable<double> WareHouse { get; set; }
        public byte[] RicePicture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDescription> BookingDescription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyDescription> BuyDescription { get; set; }
        public virtual TypeRice TypeRice { get; set; }
    }
}
